version: "3"

services:
  frontend:
    build: "./frontend"
    links:
      - backend
    networks:
      - allegro-network

  backend:
    build: "./backend"
    networks:
      - allegro-network
    expose:
      - "5000"
    links:
      - redisdb

  revproxy:
    restart: always
    build: "./nginx"
    networks:
      - allegro-network
    links:
      - frontend:frontend
      - backend:backend
    ports:
      - "80:80"

  redisdb:
    image: "redis"
    expose:
      - "6379"
    networks:
      - allegro-network

networks:
  allegro-network:
